Repository jpanther/congo, pull requests merged in 2021-12, with the labels that each got.

#45 Add leif.io to user sites
  exampleSite/content/users.md
Labels: documentation

#57 Add word counts in page meta.
  config/_default/params.toml
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fr.yaml
  i18n/pt-BR.yaml
  i18n/zh.yaml
  layouts/partials/article-meta.html
  layouts/partials/meta/word-count.html
Labels: enhancement, i18n

#61 Add dr460nf1r3.org to users
  exampleSite/content/users.md
Labels: documentation

#65 Fix error unclosed action in footer.html
  layouts/partials/footer.html
Labels: bug

#71 :lipstick: add blogger icon
  assets/icons/blogger.svg
  config/_default/config.toml
Labels: enhancement
