Repository jpanther/congo, pull requests merged in 2022-06, with the labels that each got.

#209 Added italian language
  i18n/it.yaml
Labels: i18n

#211 Update users.md
  exampleSite/content/users.md
Labels: documentation

#221 fix Netlify preview deployments
  exampleSite/content/docs/hosting-deployment/index.md
Labels: documentation

#222 Add my personal website (kelset.dev) to the list
  exampleSite/content/users.md
Labels: documentation

#224 :bug: Fix issue #223, ensure trailing forward slash baseURL during search index build
  CHANGELOG.md
  assets/js/search.js
Labels: bug, documentation

#231 Update users.md
  exampleSite/content/users.md
Labels: documentation

#234 feat: :+1: add Japanese language :jp:
  CHANGELOG.md
  i18n/ja.yaml
  package-lock.json
Labels: documentation, i18n
