Repository jpanther/congo, pull requests merged in 2022-11, with the labels that each got.

#329 fix link (upgraded to .org)
  exampleSite/content/users.md
Labels: documentation

#332 :memo: Add major.io to users list
  exampleSite/content/users.md
Labels: documentation

#349 Update button to add download tag
  exampleSite/content/docs/shortcodes/index.md
  layouts/shortcodes/button.html
Labels: enhancement

#326 :sparkles: Independent control of taxonomy display on list AND single pages
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/content/docs/configuration.md
  layouts/partials/article-meta.html
Labels: enhancement

#289 Fix error calling Paginate
  layouts/_default/term.html
Labels: question, stale

#354 Please add my website (https://www.guyu.me/) to user.md.
  exampleSite/content/users.md
Labels: documentation

#355 📝 Add bayas.dev to users.md
  exampleSite/content/users.md
Labels: documentation

#362 Added cgutierr-zgz.github.io to users
  exampleSite/content/users.md
Labels: documentation

#371 Add nl translation for Dutch / Nederlands 🇳🇱
  exampleSite/content/docs/configuration.md
  i18n/nl.yaml
Labels: i18n

#379 💄 Add support for `theme-color` meta tag
  assets/js/appearance.js
  layouts/partials/head.html
Labels: enhancement

#383 🐛 Fix code highlight issue
  assets/css/compiled/main.css
  assets/css/main.css
Labels: bug

#386 📝 Add adam.sr to users
  exampleSite/content/users.md
Labels: documentation
