Repository jpanther/congo, pull requests merged in 2022-01, with the labels that each got.

#75 Adds personal blog
  exampleSite/content/users.md
Labels: documentation

#82 :lipstick: add stackoverflow icon
  assets/icons/stackoverflow.svg
  config/_default/config.toml
Labels: enhancement

#84 🐛 add emojify for title on list page and browser / tab title
  layouts/partials/article-link.html
  layouts/partials/head.html
Labels: bug

#90 🌐 Add TR i18n
  i18n/tr.yaml
Labels: i18n

#91 💄 Adjust metadata output
  exampleSite/content/samples/placeholder-text.md
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fr.yaml
  i18n/pt-BR.yaml
  i18n/tr.yaml
  i18n/zh.yaml
  layouts/partials/article-meta.html
  layouts/partials/article-pagination.html
  layouts/partials/meta/date-updated.html
  layouts/partials/meta/date.html
Labels: enhancement, i18n
