Repository jpanther/congo, pull requests merged in 2022-04, with the labels that each got.

#159 Update users.md
  exampleSite/content/users.md
Labels: documentation

#161 Update users.md
  exampleSite/content/users.md
Labels: documentation

#166 📝 Add jeremic.ca to users
  exampleSite/content/users.md
Labels: documentation

#163 :globe_with_meridians: Add hebrew i18n
  exampleSite/content/docs/configuration.md
  i18n/he.yaml
Labels: documentation, i18n

#165 🌐 Fix footer menu display in RTL
  layouts/partials/footer.html
Labels: bug

#170 Add hungarian translation
  i18n/hu.yaml
Labels: i18n

#175 added personal site rohn.tech example
  exampleSite/content/users.md
Labels: documentation

#178 🌐 Update french i18n
  i18n/fr.yaml
Labels: i18n

#185 Finnish translation
  i18n/fi.yaml
Labels: i18n
