Repository jpanther/congo, pull requests merged in 2023-10, with the labels that each got.

#673 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#671 Fixed taxonomies display issue
  layouts/partials/article-meta.html
Labels: bug

#658 Add page context to the extend-head feature
  layouts/partials/head.html
Labels: enhancement

#669 Add Coffee and X Icons from FontAwesome
  assets/icons/coffee.svg
  assets/icons/x-twitter.svg
Labels: enhancement

#650 Small improvement in js
  assets/js/search.js
Labels: enhancement

#655 Portable markdown links
  layouts/_default/_markup/render-link.html
Labels: enhancement
