Repository jpanther/congo, pull requests merged in 2023-01, with the labels that each got.

#398 🌐 Add Indonesian translation (id.yaml) & 📝 shim to the users
  exampleSite/content/docs/configuration.md
  exampleSite/content/users.md
  i18n/id.yaml
Labels: documentation, i18n

#405 Add Mastodon sharing link
  config/_default/params.toml
  data/sharing.json
  exampleSite/config/_default/params.toml
  i18n/bn.yaml
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fi.yaml
  i18n/fr.yaml
  i18n/he.yaml
  i18n/hu.yaml
  i18n/it.yaml
  i18n/ja.yaml
  i18n/nl.yaml
  i18n/pt-BR.yaml
  i18n/pt-PT.yaml
  i18n/ro.yaml
  i18n/tr.yaml
  i18n/zh-CN.yaml
  i18n/zh-TW.yaml
Labels: enhancement, i18n

#428 Add https://kpavlov.me to users.md
  exampleSite/content/users.md
Labels: documentation

#429 Add my personal site to sample users
  exampleSite/content/users.md
Labels: documentation

#436 Add davidrothera.me to users.md
  exampleSite/content/users.md
Labels: documentation

#440 Added ethantroy.com
  exampleSite/content/users.md
Labels: documentation

#444 Add leading-relaxed to tag list
  assets/css/compiled/main.css
  layouts/partials/article-meta.html
Labels: bug

#450 Update index.md
  exampleSite/content/users/index.md
Labels: documentation

#448 🌐 Update `zh-TW` translation
  i18n/zh-TW.yaml
Labels: i18n

#446 🛠 Links render hook should add `noreferrer noopener`
  layouts/_default/_markup/render-link.html
Labels: enhancement

#452 :bug: Fix URL safety for author bio links
  layouts/partials/author-links.html
Labels: bug

#456 🐛 Remove whitespace at EOF in render-link
  layouts/_default/_markup/render-link.html
Labels: bug
