Repository jpanther/congo, pull requests merged in 2023-11, with the labels that each got.

#694 Add icon for the threads social network
  assets/icons/threads.svg
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
Labels: documentation, enhancement

#696 Fix typo in Dutch translation
  i18n/nl.yaml
Labels: i18n

#703 Add Ukrainian Localization
  i18n/uk.yaml
Labels: i18n

#718 🌐 Added Bulgarian Language
  i18n/bg-BG.yaml
Labels: i18n

#714 Remove unnecessary execute permissions
  exampleSite/content/_index.es.md
  exampleSite/content/_index.md
  exampleSite/content/docs/_index.md
  exampleSite/content/samples/_index.es.md
  exampleSite/content/samples/_index.md
  exampleSite/content/samples/charts/index.es.md
  exampleSite/content/samples/charts/index.md
  exampleSite/content/samples/diagrams-flowcharts/index.es.md
  exampleSite/content/samples/diagrams-flowcharts/index.md
  exampleSite/content/samples/emoji/index.es.md
  exampleSite/content/samples/emoji/index.ja.md
  exampleSite/content/samples/emoji/index.md
  exampleSite/content/samples/external/index.es.md
  exampleSite/content/samples/external/index.ja.md
  exampleSite/content/samples/external/index.md
  exampleSite/content/samples/markdown/index.es.md
  exampleSite/content/samples/markdown/index.ja.md
  exampleSite/content/samples/markdown/index.md
  exampleSite/content/samples/mathematical-notation/index.es.md
  exampleSite/content/samples/mathematical-notation/index.md
  exampleSite/content/samples/placeholder-text/index.es.md
  exampleSite/content/samples/placeholder-text/index.ja.md
  exampleSite/content/samples/placeholder-text/index.md
  exampleSite/content/samples/rich-content/index.es.md
  exampleSite/content/samples/rich-content/index.ja.md
  exampleSite/content/samples/rich-content/index.md
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/site.webmanifest
Labels: documentation

#691 Print warning if system can't resolve link to a markdown file
  layouts/_default/_markup/render-link.html
Labels: enhancement

#693 feat: picture partial
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  layouts/_default/_markup/render-image.html
  layouts/_default/single.html
  layouts/partials/picture.html
  layouts/shortcodes/figure.html
  layouts/shortcodes/screenshot.html
Labels: enhancement

#646 Add quicklink
  assets/js/quicklink.js
  assets/lib/quicklink/quicklink.umd.js
  exampleSite/config/_default/params.toml
  layouts/partials/head.html
  package-lock.json
  package.json
Labels: enhancement

#705 fix: close menu button on click
  assets/js/menu.js
  exampleSite/config/_default/params.toml
  layouts/partials/head.html
  layouts/partials/header/hamburger.html
  layouts/partials/header/hybrid.html
Labels: bug

#719 feat: add share options
  assets/icons/line.svg
  data/sharing.json
  exampleSite/config/_default/params.toml
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
  i18n/ar.yaml
  i18n/bg.yaml
  i18n/bn.yaml
  i18n/cs.yaml
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fi.yaml
  i18n/fr.yaml
  i18n/he.yaml
  i18n/hu.yaml
  i18n/id.yaml
  i18n/it.yaml
  i18n/ja.yaml
  i18n/nl.yaml
  i18n/pl.yaml
  i18n/pt-BR.yaml
  i18n/pt-PT.yaml
  i18n/ro.yaml
  i18n/ru.yaml
  i18n/sk.yaml
  i18n/tr.yaml
  i18n/uk.yaml
  i18n/zh-CN.yaml
  i18n/zh-TW.yaml
Labels: enhancement, i18n
