Repository jpanther/congo, pull requests merged in 2023-12, with the labels that each got.

#731 Add Korean language support
  i18n/ko.yaml
Labels: i18n

#757 🐛 update labeller to use v5 config
  .github/labeller.yml
Labels: bug

#755 ✨ add google scholar profile icon
  assets/icons/google-scholar.svg
  config/_default/languages.en.toml
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
Labels: documentation

#750 Added Japanese localization for sharing to the Mastodon.
  i18n/ja.yaml
Labels: i18n

#733 Add scrolling over TOC
  assets/css/compiled/main.css
  assets/css/main.css
Labels: enhancement

#753 🐛 Add CSS overflow/wrapping on KaTeX, tables, and code sections
  assets/css/compiled/main.css
  assets/css/main.css
Labels: bug

#756 ✨ more profiles and share links
  assets/icons/mendeley.svg
  assets/icons/weibo.svg
  config/_default/languages.en.toml
  config/_default/params.toml
  data/sharing.json
  exampleSite/config/_default/params.toml
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
  i18n/ar.yaml
  i18n/bg.yaml
  i18n/bn.yaml
  i18n/cs.yaml
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fi.yaml
  i18n/fr.yaml
  i18n/he.yaml
  i18n/hu.yaml
  i18n/id.yaml
  i18n/it.yaml
  i18n/ja.yaml
  i18n/ko.yaml
  i18n/nl.yaml
  i18n/pl.yaml
  i18n/pt-BR.yaml
  i18n/pt-PT.yaml
  i18n/ro.yaml
  i18n/ru.yaml
  i18n/sk.yaml
  i18n/tr.yaml
  i18n/uk.yaml
  i18n/zh-CN.yaml
  i18n/zh-TW.yaml
Labels: documentation, enhancement, i18n

#762 :memo: Adds personal site to users example
  exampleSite/content/users/index.md
Labels: documentation

#751 :lipstick: update CSS Schemas to include TW3.3+ 950 color variants
  assets/css/schemes/avocado.css
  assets/css/schemes/cherry.css
  assets/css/schemes/congo.css
  assets/css/schemes/fire.css
  assets/css/schemes/ocean.css
  assets/css/schemes/sapphire.css
  assets/css/schemes/slate.css
Labels: enhancement
