Repository jpanther/congo, pull requests merged in 2024-04, with the labels that each got.

#844 Add hosni.info as user of the theme
  exampleSite/content/users/index.md
Labels: documentation

#845 Add Vietnamese Localization
  i18n/vi.yaml
Labels: i18n

#852 Add Swedish localization
  i18n/sv.yaml
Labels: i18n

#851 Add icon for Bluesky social network
  assets/icons/bluesky.svg
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
  exampleSite/content/samples/icons/index.zh-cn.md
Labels: documentation, enhancement

#832 Add support for Umami Analytics
  README.md
  config/_default/params.toml
  exampleSite/config/_default/params.toml
  exampleSite/content/docs/configuration/index.md
  exampleSite/content/docs/partials/index.md
  layouts/partials/analytics.html
Labels: documentation, enhancement

#849 :sparkles: add defaultThemeColor option
  config/_default/params.toml
  exampleSite/content/docs/configuration/index.ja.md
  exampleSite/content/docs/configuration/index.md
  exampleSite/content/docs/configuration/index.zh-cn.md
  layouts/partials/head.html
Labels: documentation, enhancement

#850 add personal site to users list
  exampleSite/content/users/index.md
Labels: documentation

#859 Add noamlerner.com to users
  exampleSite/content/users/index.md
Labels: documentation
