Repository jpanther/congo, pull requests merged in 2024-01, with the labels that each got.

#767 Add site to list of users
  exampleSite/content/users/index.md
Labels: documentation

#764 fix: fix extra ß symbol
  layouts/_default/single.html
Labels: bug

#776 docs: Add Chinese documentation for github page.
  exampleSite/config/_default/languages.zh-CN.toml
  exampleSite/config/_default/menus.zh-CN.toml
  exampleSite/content/_index.zh-cn.md
  exampleSite/content/docs/_index.zh-cn.md
  exampleSite/content/docs/advanced-customisation/index.zh-cn.md
  exampleSite/content/docs/configuration/index.zh-cn.md
  exampleSite/content/docs/content-examples/index.zh-cn.md
  exampleSite/content/docs/front-matter/index.zh-cn.md
  exampleSite/content/docs/getting-started/index.zh-cn.md
  exampleSite/content/docs/homepage-layout/index.zh-cn.md
  exampleSite/content/docs/hosting-deployment/index.zh-cn.md
  exampleSite/content/docs/installation/index.zh-cn.md
  exampleSite/content/docs/partials/index.zh-cn.md
  exampleSite/content/docs/shortcodes/index.zh-cn.md
  exampleSite/content/docs/version-2/_index.zh-cn.md
  exampleSite/content/docs/version-2/upgrade/index.zh-cn.md
  exampleSite/content/samples/_index.zh-cn.md
  exampleSite/content/samples/charts/index.zh-cn.md
  exampleSite/content/samples/diagrams-flowcharts/index.zh-cn.md
  exampleSite/content/samples/emoji/index.zh-cn.md
  exampleSite/content/samples/external/index.zh-cn.md
  exampleSite/content/samples/icons/index.zh-cn.md
  exampleSite/content/samples/markdown/index.zh-cn.md
  exampleSite/content/samples/mathematical-notation/index.zh-cn.md
  exampleSite/content/samples/placeholder-text/index.zh-cn.md
  exampleSite/content/samples/rich-content/index.zh-cn.md
  exampleSite/content/tags/_index.zh-CN.md
  exampleSite/content/tags/advanced/_index.zh-CN.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#789 💄 Fix Safari status bar style
  assets/js/appearance.js
  layouts/partials/head.html
Labels: enhancement

#788 Fix vertical offset when using locale switcher
  layouts/partials/translations.html
Labels: bug

#769 Add jamesjarvis.io to list of users
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#777 Add jnsgr.uk to list of users
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#781 add stupidjoey.net
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#790 Added my personal blog to users section.
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#786 Do not render article-meta figure if there is nothing to display
  layouts/_default/single.html
Labels: bug

#730 fix bug in picture with params
  layouts/_default/_markup/render-image.html
  layouts/_default/single.html
  layouts/partials/picture.html
  layouts/shortcodes/figure.html
  layouts/shortcodes/screenshot.html
Labels: bug

#785 Fix picture partial img/source attributes
  layouts/partials/picture.html
Labels: bug

#741 :recycle: Render author image with picture partial
  layouts/partials/author.html
  layouts/partials/home/profile.html
Labels: enhancement

#792 Add one entry to congo users table
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-cn.md
Labels: documentation

#778 feat: use meta tag to redirect externalURLs
  layouts/partials/head.html
Labels: enhancement
