Repository jpanther/congo, pull requests merged in 2024-10, with the labels that each got.

#932 📝 Add socrabytes.github.io to the user list
  exampleSite/content/users/index.md
Labels: documentation

#921 Replace .Site.IsMultiLingual with hugo.IsMultilingual
  layouts/partials/footer.html
  layouts/partials/header/basic.html
  layouts/partials/header/hamburger.html
  layouts/partials/header/hybrid.html
  layouts/partials/translations.html
  netlify.toml
Labels: bug

#933 feat: Add sharing link and icons for XING
  assets/icons/xing.svg
  config/_default/languages.en.toml
  data/sharing.json
  exampleSite/config/_default/params.toml
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
  exampleSite/content/samples/icons/index.zh-Hans.md
  i18n/ar.yaml
  i18n/bg.yaml
  i18n/bn.yaml
  i18n/cs.yaml
  i18n/de.yaml
  i18n/en.yaml
  i18n/es.yaml
  i18n/fi.yaml
  i18n/fr.yaml
  i18n/he.yaml
  i18n/hu.yaml
  i18n/id.yaml
  i18n/it.yaml
  i18n/ja.yaml
  i18n/ko.yaml
  i18n/nb.yaml
  i18n/nl.yaml
  i18n/pl.yaml
  i18n/pt-BR.yaml
  i18n/pt-PT.yaml
  i18n/ro.yaml
  i18n/ru.yaml
  i18n/sk.yaml
  i18n/sv.yaml
  i18n/ta.yaml
  i18n/tr.yaml
  i18n/uk.yaml
  i18n/vi.yaml
  i18n/zh-Hans.yaml
  i18n/zh-Hant.yaml
Labels: documentation, enhancement, i18n

#951 📝 Add montenegrodanielfelipe.com to the user list
  exampleSite/content/users/index.md
Labels: documentation
