Repository jpanther/congo, pull requests merged in 2024-08, with the labels that each got.

#887 Add clementfouque.com site to the list of users
  exampleSite/content/users/index.md
Labels: documentation

#885 🎨 Add breadcrumb to schema data
  layouts/partials/schema.html
Labels: enhancement

#901 fix: fix unsafe url
  README.md
Labels: documentation

#872 Add Norwegian localisation
  i18n/nb.yaml
Labels: i18n

#896 add victoryuan.com to users
  exampleSite/content/users/index.md
Labels: documentation

#902 Add chenyu.blog as user
  exampleSite/content/users/index.md
Labels: documentation

#915 aimtune.dev added
  exampleSite/content/users/index.md
Labels: documentation

#920 Add blog.ny4.dev to users
  exampleSite/content/users/index.md
Labels: documentation
