Repository jpanther/congo, pull requests merged in 2025-02, with the labels that each got.

#976 Add Ko-fi
  assets/icons/kofi.svg
  config/_default/languages.en.toml
Labels: documentation, enhancement

#985 Docs: List languages.en.toml in config
  exampleSite/content/docs/installation/index.md
Labels: documentation

#1005 Documentation: update information on pagination
  exampleSite/content/docs/configuration/index.ja.md
  exampleSite/content/docs/version-2/upgrade/index.ja.md
  exampleSite/content/docs/version-2/upgrade/index.md
Labels: documentation

#1007 Remove documentation on deprecated shortcode 'gist'
  exampleSite/content/samples/rich-content/index.de.md
  exampleSite/content/samples/rich-content/index.es.md
  exampleSite/content/samples/rich-content/index.ja.md
  exampleSite/content/samples/rich-content/index.md
  exampleSite/content/samples/rich-content/index.zh-Hans.md
Labels: documentation

#986 🐛 Fix: Correct absolute path for shebang in shell script
  release.sh
Labels: bug

#1012 Just fixed two minor typos ran into
  CHANGELOG.md
Labels: documentation

#994 📝 Modify noamlerner.com's base url in the users page
  exampleSite/content/users/index.md
Labels: documentation

#990 :bug: Fix: incorrect translation link in multihost mode #988
  layouts/partials/translations.html
Labels: bug

#983 🍱 Reduce size of favicons
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
Labels: enhancement

#996 Add euangelos.linardos.gr to the user list
  exampleSite/content/users/index.md
Labels: documentation

#1000 :memo: Add joshquinlan.co.uk to user list
  exampleSite/content/users/index.md
Labels: documentation

#1002 Add blog.sky123.top to user list
  exampleSite/content/users/index.es.md
  exampleSite/content/users/index.ja.md
  exampleSite/content/users/index.md
  exampleSite/content/users/index.zh-Hans.md
Labels: documentation

#1008 Update index.md
  exampleSite/content/users/index.md
Labels: documentation

#1010 add wendyliga.com
  exampleSite/content/users/index.md
Labels: documentation

#952 Update index.md
  exampleSite/content/users/index.md
Labels: documentation

#1022 Update sharing.json to add bluesky
  data/sharing.json
Labels: enhancement
