Repository jpanther/congo, pull requests merged in 2025-06, with the labels that each got.

#1037 Add personal blog to the users page
  exampleSite/content/users/index.md
Labels: documentation

#1046 :sparkles: Add `canonicalUrl` parameter
  CHANGELOG.md
  layouts/partials/head.html
Labels: documentation, enhancement

#1055 Refined CS translation
  i18n/cs.yaml
Labels: i18n

#1057 Add: `goodreads` icon
  .gitignore
  assets/icons/goodreads.svg
  exampleSite/content/samples/icons/index.de.md
  exampleSite/content/samples/icons/index.es.md
  exampleSite/content/samples/icons/index.ja.md
  exampleSite/content/samples/icons/index.md
  exampleSite/content/samples/icons/index.zh-Hans.md
Labels: documentation, enhancement

#1065 Add missing space in the LINE sharing link
  data/sharing.json
Labels: bug

#1038 add cmp1315.com to the list of users
  exampleSite/content/users/index.md
Labels: documentation

#1073 layouts: correctly check for template existence
  exampleSite/layouts/partials/home/custom.html
  layouts/_default/baseof.html
  layouts/index.html
Labels: bug

#1072 assets: add rss and podcast icons
  assets/icons/podcast.svg
  assets/icons/rss.svg
Labels: enhancement

#1075 layouts: update `partials` to `_partials`
  layouts/_partials/article-link.html
  layouts/_partials/footer.html
  layouts/_partials/head.html
  layouts/baseof.html
  layouts/single.html
Labels: bug
